1023 Use SQL classifiers
ONSdigital/census-rm-ops pull request #34
Opened 2020-07-03 09:02 UTC by AdamHawtin

# Motivation and Context
Classifiers have become an SQL where clause that must now also contain the HI case filter.

# What has changed
* Change classifiers JSON text area to SQL string
* Validate where clause is not empty
* Improve docker file (more caching, less unnecessary installation)
* Improve action types drop down
* Update tests

# How to test?
Build and run locally with other ticket branches, check the action rules page still function correctly and the correct action rule gets created in the DB from the UI.

# Links
https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13

# Screenshots (if appropriate):
![Default where clause example](https://user-images.githubusercontent.com/35268982/86452367-1b1b7000-bd14-11ea-878f-8f4097a0dc0d.png)
![Action types dropdown improvements](https://user-images.githubusercontent.com/35268982/86452384-2373ab00-bd14-11ea-8930-2638be6cad8d.png)

2020-07-03 09:03 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Address Frame Delta - generate additional initial contact files (13)](https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13)

2020-07-07 08:02 UTC, NickGrantX requested changes
Classifiers are still classifiers, not "user defined" as stated on other PRs

2020-07-07 13:09 UTC, NickGrantX approved these changes

2020-07-08 06:36 UTC, LukeLoze1 approved these changes

2020-07-08 07:41 UTC, merged